FROM alpine
WORKDIR /app
ENV TZ=Asia/Shanghai
RUN apk add --no-cache alpine-conf ca-certificates &&\
    /usr/sbin/setup-timezone -z Asia/Shanghai && \
    apk del alpine-conf && \
    rm -rf /var/cache/apk/*
COPY subs-check /app/subs-check
RUN chmod +x /app/subs-check
CMD ["/app/subs-check"]
EXPOSE 8199
EXPOSE 8299
